### ISSUE TITLE
Migration of ElasticSearch plugin

### ISSUE THREAD

**Issue by ipapapa** [Netflix/ndbench#1]
We need to add the ES plugin in the OSS.

**Comment by toff63** [comment]
@vinaykumarchella do you have an idea when this plugin will be available?

Thanks

**Comment by vinaykumarchella** [comment]
@toff63 We did not prioritize it yet but should be an easy one, I can get it out next week. If you have it already, please feel free to send a PR.

**Comment by toff63** [comment]
@vinaykumarchella next week would be great. I don't have the plugin ready for PR. As I am about to perform some perf testing on Elasticsearch, I was wondering if I should consider using ndbench for that or not.
