### ISSUE TITLE
Add more logging to init() method of KeyGenerator (beginning, end)

### ISSUE THREAD

**Issue by amcp** [Netflix/ndbench#112]

**Comment by vinaykumarchella** [comment]
Currently, KeyGenerator init implementors provide enough logging during the initialization phase which could take longer depending on the input parameters. What extra logging are you looking for?

Sample logging:

`Still initializing sample data for Keys. So far: 5/100`

**Comment by amcp** [comment]
Correct, this was an artifact of my debugging. Closing.
