### ISSUE TITLE
Does ndbench directly injection workloads to data store systems? without considering different microservices?

### ISSUE THREAD

**Issue by hopingjuly** [Netflix/ndbench#16]
different microservices hava different data amount ,data type and data size, is it necessary to consider these differences ?

**Comment by vinaykumarchella** [comment]
_Data Amount and data size can be configured using_  - https://github.com/Netflix/ndbench/blob/master/ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java#L25-L28.

_DataType can be implemented in Plugin as per the different data store._ 
E.g, 

- Inserting Json document - https://github.com/Netflix/ndbench/blob/master/ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsPlugin.java#L88-L93'

- Inserting plain String - https://github.com/Netflix/ndbench/blob/master/ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java#L139

So, plugin developer can choose any data type as per microservice / datastore and use it accordingly.

**Comment by vinaykumarchella** [comment]
Closing this issue since we did not hear lately on this.
