### ISSUE TITLE
starting up with ndbench

### ISSUE THREAD

**Issue by ankitpateledu** [Netflix/ndbench#17]
hello 

I have limited exposure in data store systems and cloud. 
I am planning on evaluating ndbench for a particular usecase. i need help setting ndbench up and get going.
I have following questions to begin with 
	1. What is minimum count of serverboxes i need to start ? do you have minimum HW configuration requirements?
	2. What SW/stack framework do i need to set up? i.e. specific hadoop or cassandra version or other framework? 
	3. how to install ndbench on my setup, integrate with framework (hadoop/cassandra/etc) and run the benchmark?
	4. what kind if score or result ndbech generate and how to interpret it ?

thanks
Ankit

**Comment by ipapapa** [comment]
Hello @ankitpateledu 
1. You can use a single server or as many servers as you like.
2. There are [two plugins](https://github.com/Netflix/ndbench/tree/master/ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass) for Cassandra, one with Thrift (using Astyanax) and one with CQL.
3. You can do `./gradlew appRun` to just run locally or you can deploy the .war in a Tomcat server
4. You can see the output in the [UI](https://github.com/Netflix/ndbench/wiki/NDBench-UI).

**Comment by ipapapa** [comment]
Since the question seems to have been addressed and there is no further follow-up for some time now, I will close this issue. Please feel free to reopen this or another one if you need any further assistance.
