### ISSUE TITLE
Broken release due to DaxJavaClient resolution

### ISSUE THREAD

**Issue by vinaykumarchella** [Netflix/ndbench#197]
Gradle does not let ndbench artifacts to publish to maven central since one of its dependencies are not resolvable. Everything we publish to there needs to be resolvable, adding a custom jar to the classpath makes it unusable to the wide world, the pom generation is pickier and notices a missing version value and does not let build pass, as a result, our travis ci builds are broken since #191 merge.

**Comment by vinaykumarchella** [comment]
As part of this ticket, we will be disabled the plugins where there is a dependency on daxjavaclient, untill it is published in MavenCentral to unblock the release of ndbench.

**Comment by vinaykumarchella** [comment]
Fixed it as part of https://github.com/Netflix/ndbench/pull/198

**Comment by amcp** [comment]
@vinaykumarchella @ipapapa I will look into this issue.
