### ISSUE TITLE
Connecting to oracle databases?

### ISSUE THREAD

**Issue by leeadh** [Netflix/ndbench#207]
Is there a way to connect to ndbench for oracle databases and using an oracle wallet?

**Comment by vinaykumarchella** [comment]
Yes, you can. You can write a ndbench plugin to connect to it, here are the instructions to write a plugin - https://github.com/Netflix/ndbench/wiki/Compiled-Plugin. There is no existing plugin for Oracle.

**Comment by leeadh** [comment]
hi vinay thank you for this. Can you guide me how to do this exactly?

**Comment by vinaykumarchella** [comment]
Closing this issue based on silence==everything is good
