### ISSUE TITLE
Update in wiki NDBench ES Tutorial

### ISSUE THREAD

**Issue by SouzaGuilherme** [Netflix/ndbench#233]
Update:
`docker run  -d -e xpack.security.enabled=false --name=elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.6.2`

Previous:
`docker run  -e xpack.security.enabled=false --name=elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.3`

Previous the container did not run in the background and had problems finding the copy in the public records, searching the official website and modifying the command and making some addition, now it works right!

**Comment by vinaykumarchella** [comment]
Thank you @SouzaGuilherme for reporting, updated wiki accordingly.
