### ISSUE TITLE
Wiki doesn't go anywhere & there's no Wiki link

### ISSUE THREAD

**Issue by jameswomack** [Netflix/ndbench#4]
> "Details about the features can be found in the Wiki"

The "Wiki" text, when clicked, doesn't do anything but reload the page.

**Comment by ipapapa** [comment]
@jameswomack we will be enabling the Wiki shortly and the link will work. We will be working on populating the wiki in the next few days as well. Thanks for reporting this.

**Comment by ipapapa** [comment]
The issue has been fixed.

**Comment by kw217** [comment]
This doesn't appear to be fixed. I raised #5 before I noticed this issue.
