### ISSUE TITLE
AWS failure to load modules

### ISSUE THREAD

**Issue by ipapapa** [Netflix/ndbench#40]
New GuiceModule that an environment is loaded based on properties has an issue with AWS deployments #32

**Comment by pprojetc00** [comment]
In New GuiceModul, seem code should work okay, but when trying to build app, is not getting host-name. however previous version working properly

**Comment by ipapapa** [comment]
@pprojetc00 Currently the default platform in the `manifest.yml` seems to be CF. I have submitted a PR to change that to `LOCAL` (although AWS and CF are only supported and anything else will be local) https://github.com/Netflix/ndbench/pull/41. I was wondering if you tried with something other than `CF` or `AWS`.
