### ISSUE TITLE
meta10?

### ISSUE THREAD

**Issue by siculars** [Netflix/ndbench#47]
https://github.com/Netflix/ndbench/blob/1bf0af6dd676f9ccb0d8b3871399b8d68799590b/ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AWSLocalClusterDiscovery.java#L32

Are you sure that's correct?

```
ubuntu@ip-172-31-28-231:~$ curl http://169.254.169.254/latest/meta10-data/local-hostname
> <?xml version="1.0" encoding="iso-8859-1"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
>          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
>  <head>
>   <title>404 - Not Found</title>
>  </head>
>  <body>
>   <h1>404 - Not Found</h1>
>  </body>
> </html>


ubuntu@ip-172-31-28-231:~$ curl http://169.254.169.254/latest/meta-data/local-hostname

ip-172-31-28-231.us-west-2.compute.internal
```

**Comment by ipapapa** [comment]
I guess @diegopacheco would be the appropriate person to answer this.

**Comment by diegopacheco** [comment]
@ipapapa 

There are mode documentation here. This is the AWS Metadata API http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

Looks like there is typo there - we need to remove the *10* from the URL.

Nice catch @siculars 

Cheers,
Diego Pacheco

**Comment by ipapapa** [comment]
Do you guys want to do a PR?

**Comment by ipapapa** [comment]
Fixed
