### ISSUE TITLE
Why is an ASG needed for running ndbench?

### ISSUE THREAD

**Issue by darkpssngr** [Netflix/ndbench#50]
How will the instance booted by the autoscale group automatically join the cluster? The AWSLocalClusterDiscovery seems to only get the host machine's IP. And If we don't create an AMI with ndbench already installed then what is the point of having an ASG?

Have I misunderstood something ? Please clarify.

Thanks

**Comment by wpc** [comment]
same question here

**Comment by vinaykumarchella** [comment]
ASG is to auto detect all the nodes under that ASG and form NDBench cluster. Correct, `AWSLocalClusterDiscovery` dint do the right thing, hence added `https://github.com/Netflix/ndbench/blob/master/ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AwsAsgDiscovery.java`. We have an AMI with ndbench already installed, open to make one for public. But the idea under ASG such that instace terminations other stuff is taken care by ASG and all the nodes in the ASG are discovered and form a NDBench Cluster. Hope this helps.

**Comment by vinaykumarchella** [comment]
Considering this as resolved, please reopen if you see any issues.
